package x.mvmn.gphoto2.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/local/include/gphoto2/gphoto2/gphoto2-filesys.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CameraFileInfo extends Structure {
	/** C type : CameraFileInfoPreview */
	public CameraFileInfoPreview preview;
	/** C type : CameraFileInfoFile */
	public CameraFileInfoFile file;
	/** C type : CameraFileInfoAudio */
	public CameraFileInfoAudio audio;
	public CameraFileInfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("preview", "file", "audio");
	}
	/**
	 * @param preview C type : CameraFileInfoPreview<br>
	 * @param file C type : CameraFileInfoFile<br>
	 * @param audio C type : CameraFileInfoAudio
	 */
	public CameraFileInfo(CameraFileInfoPreview preview, CameraFileInfoFile file, CameraFileInfoAudio audio) {
		super();
		this.preview = preview;
		this.file = file;
		this.audio = audio;
	}
	public CameraFileInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CameraFileInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends CameraFileInfo implements Structure.ByValue {
		
	};
}
