package x.mvmn.gphoto2.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/local/include/gphoto2/gphoto2/gphoto2-camera.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CameraText extends Structure {
	/**
	 * < \brief Character string containing the translated text.<br>
	 * C type : char[32 * 1024]
	 */
	public byte[] text = new byte[32 * 1024];
	public CameraText() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("text");
	}
	/**
	 * @param text < \brief Character string containing the translated text.<br>
	 * C type : char[32 * 1024]
	 */
	public CameraText(byte text[]) {
		super();
		if ((text.length != this.text.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.text = text;
	}
	public CameraText(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CameraText implements Structure.ByReference {
		
	};
	public static class ByValue extends CameraText implements Structure.ByValue {
		
	};
}
